### PR TITLE
New Icons and Logotypes

### PR DESCRIPTION
**Pull request by Tobaloidee**
Includes New Icons and Logotypes (Blue, White & Black versions) :)

### CODE REVIEW

**Comment by hendricius** [comment]
Thank you, amazing!

**Comment by Tobaloidee** [comment]
My pleasure to help Sir! Thanks again and best regards!

**Comment by Tobaloidee** [comment]
Hey @sue Sure! Ill visit your page first to know something about your project or you can feed me with something that you like..I will work on it as soon as i get home maybe 5hrs from now.. :)

**Comment by su8** [comment]
@Tobaloidee Can you add some symbol (computer parts, code etc.) to the following text

**Comment by Tobaloidee** [comment]
Ill show you my output on your page @su8

**Comment by Tobaloidee** [comment]
Hey @sue, I have created an issue in your pinkybar repository  regarding your logo request here. please check it out. thanks! :)

**Pull request merged**
