### PR TITLE
Add lavash bread recipe

### PR DESCRIPTION
**Pull request by amiiy**
Add lavash bread.
there are too many type of recipe for this bread, i currently searching for tasty one to add.

### CODE REVIEW

**Comment by hendricius** [comment]
Looks amazing. Do you think you can add the full recipe? Is it made with yeast?

**Comment by amiiy** [comment]
Yes! 
in some recipes add little yeast when preparing the dough.

**Comment by hendricius** [comment]
Could you when you have a chance add the full recipe? That would be great. Thanks.

**Comment by hendricius** [comment]
Closing this for now, let know when I should reopen it.

**Pull request closed without merging**
