### PR TITLE
Spell check all files

### PR DESCRIPTION
**Pull request by akx**
I've manually spell-checked all files.

In addition to some typo fixing and grammar tuning, I've re-wrapped some long lines to make the original .md easier to read and modify, but these changes should not affect the rendered output.

Looking forward to baking some of these!

### CODE REVIEW

**Comment by hendricius** [comment]
Thanks a bunch. There seem to be some merge conflicts now with the previous merges. Sometimes I did not break the lines on purpose because the content should stay together. I usually only started new lines when I thought it's now a different paragraph with different content.

Let me check later how it looks like and revert. If it's visually the same in the rendered output, this is great. Sticking to the 80-100 characters per line is sweet, then my editor won't complain too.

**Comment by hendricius** [comment]
Used your strategy here: https://github.com/hendricius/the-bread-code/blob/master/basics/common-problems-faq.md. Definitely much easier to read in VIM :).

**Comment by akx** [comment]
@hendricius Rebased on top of current master, and spell-checked the FAQ a bit too :)

**Comment by akx** [comment]
By the way, if you _do_ want a wrapped newline to affect the rendered output, add two spaces (`  `) before the newline, as per the [hard line breaks](http://spec.commonmark.org/0.28/#hard-line-breaks) bit of the Markdown spec :)

**Comment by akx** [comment]
EDIT: I also added an `aspell` wrapper script for programmatic spellchecking of files :)

**Comment by hendricius** [comment]
Well done, love it.

Do you think we can setup a CI or something to automatically spell check every pull request?

**Comment by akx** [comment]
@hendricius Definitely! Would you prefer Travis or Circle or something else?

**Pull request merged**
