### PR TITLE
Restructured texts

### PR DESCRIPTION
**Pull request by PhilippMeissner**
I tried to make the setup and different dough's a little more clear throughout the guide.
Maybe we can agree on the wording and use it throughout the entire repo?

I would suggest:
> `Mother dough` - The sour dough that we fed for at least 7 days and keep on feeding until we die or Trump starts WW III.

> `Starter dough` -  The sour dough we "steal" from our mother dough. We usually add more flour and water to it. Later on, we feed what is left of it back to our mother dough.

> `Basic dough` - The combination of our "finished" starter dough and the other ingredients (In the basic-bread example that is: `flour, water, salt`).

### CODE REVIEW

**Comment by hendricius** [comment]
Thanks a bunch. `rest of what is left back from it back` there might be a small typo.

Also it should be 2% of salt on the final product. Let's say you have 500 grams of flour and 200 grams of starter then you need to calculate 2% based on 700 grams.

**Comment by PhilippMeissner** [comment]
> Also it should be 2% of salt on the final product. Let's say you have 500 grams of flour and 200 grams of starter then you need to calculate 2% based on 700 grams.

Okay, then we need to clarify how many % of _what_ we need. Ingredients state:

```
- 500 grams of flour
- 325 grams or 65% of water (means 100% is 500g, which is the *flour mass*. So better: 65% of *flour mass* (?))
- 200 grams or 40% of sour dough (means 100% again is 500g, which is the *flour mass* again. So better: 40% of *flour mass* (?))
- 14 grams or 2% of salt (means 100% is 500g, which apparently means % of *flour mass* + *starter dough mass*. What about the water, does its mass not influence the salt percentage necessary?)

**Comment by hendricius** [comment]
Yes. Actually if we are 100% correct it should be 2% on the flour. The percentage is always calculated based on the total flour ingredients you add. If the sourdough starter has 50% hydration and 50% flour the correct net weight would be 600 grams. Then 2% based on 600 grams, 12 grams of salt.

**Comment by hendricius** [comment]
Also your points are valid. We can change it that way. Although we might want to consider adding this to the `basic-dough.md` recipe. As it is the same for the non sourdough breads.

**Comment by hendricius** [comment]
Thanks a bunch! Great feedback additions. How did you first bread turn out?

**Comment by PhilippMeissner** [comment]
Unfortunately  I had no time to prepare it the day after we talked. I will bake this weekend finally :)

**Pull request merged**
