### PR TITLE
Sandwich loaf?

### PR DESCRIPTION
**Pull request by nimbius**
Ive written a recipe for a regular sandwich loaf :)

### CODE REVIEW

**Comment by hendricius** [comment]
Awesome. It seems we added the one recipe twice - the pasta one. Could that be?

Thanks.

**Comment by nimbius** [comment]
Strange, this should be a recipe for a sandwich loaf...perhaps I'm missing a commit or push

On June 15, 2018 5:24:35 AM PDT, Hendrik Kleinwaechter <notifications@github.com> wrote:
>Awesome. It seems we added the one recipe twice - the pasta one. Could
>that be?
>
>Thanks.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hendricius/the-bread-code/pull/105#issuecomment-397604554

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hendricius** [comment]
Need help? I can clean it up 👍

**Comment by hendricius** [comment]
@nimbius wanted to bake this one :). Can you clean up the PR then we merge it? Else I can also do that real quick :). Thanks!

**Comment by nimbius** [comment]
I have the option to resolve conflicts, however im not sure what the option does in github?  it seems grayed out.  line 64-67 appear in the readme as conflicting.

https://github.com/hendricius/the-bread-code/pull/105/commits/6363288a433f555a2365f52c63e13c07f80ab968

this appears to be the correct part of the commit for the sandwich loaf.  Am i missing something? :)

**Comment by hendricius** [comment]
Yep, exactly that commit I think. I gave you write access too. Hope that helps. If not let me know :)

**Comment by nimbius** [comment]
Thanks! ive updated the readme to resolve the conflict :)

**Pull request merged**
