### PR TITLE
added sourdough pasta

### PR DESCRIPTION
**Pull request by nimbius**
a nice recipe for sourdough pasta using our recently learned starter :)

### CODE REVIEW

**Comment by hendricius** [comment]
Wow - amazing. Do you have some pictures of the result?

**Comment by nimbius** [comment]
I should have a few this evening :)

**Comment by nimbius** [comment]
img_20180608_224426
img_20180608_225026
img_20180608_225625
img_20180608_232258

the last image is a quick dish i made with the pasta
sourdough linguini aglio e olio with
portobello mushrooms, and pan seared northern California scallops on a bed of arugula-almond pesto.  

Any interest in my recipe for German sourdough spaetzle?

**Comment by tholemu** [comment]
Absolutely beautiful. Thank you for sharing!

 
 
  On Fri, Jun 8, 2018 at 22:43, John<notifications@github.com> wrote:   





the last image is a quick dish i made with the pasta
sourdough linguini aglio e olio with
portobello mushrooms, and pan seared northern California scallops on a bed of arugula-almond pesto.

Any interest in my recipe for German sourdough spaetzle?

**Comment by hendricius** [comment]
Well done. It looks really good.

- [ ] Could you also add the pictures to the recipe?
- [ ] Could you then link it from the Readme?

Thanks!

**Comment by nimbius** [comment]
Ive updated the readme and added images as requested.

**Comment by hendricius** [comment]
Thank you!

**Pull request merged**
